"""Runs spec/testdata/ml_dsa_65_vectors.json (generated by Go's crypto/mldsa)
through the from-scratch Python verifier."""

from __future__ import annotations

import base64
import json
import os
import sys
import time
import unittest

SPEC_DIR = os.path.dirname(os.path.abspath(__file__))
if SPEC_DIR not in sys.path:
    sys.path.insert(0, SPEC_DIR)

import ml_dsa_65

VECTORS = os.path.join(SPEC_DIR, "testdata", "ml_dsa_65_vectors.json")


class MlDsa65VectorTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        with open(VECTORS, "r", encoding="utf-8") as handle:
            cls.vectors = json.load(handle)

    def test_keys_and_case_mix(self) -> None:
        self.assertGreaterEqual(len(self.vectors["keys"]), 6)
        expected = [c["expected"] for c in self.vectors["cases"]]
        self.assertGreaterEqual(expected.count(True), 10)
        self.assertGreaterEqual(expected.count(False), 15)

    def test_every_case(self) -> None:
        keys = self.vectors["keys"]
        for case in self.vectors["cases"]:
            pk_hex = case.get("public_key_hex") or keys[case["key"]]["public_key_hex"]
            with self.subTest(case=case["name"]):
                got = ml_dsa_65.verify(
                    bytes.fromhex(pk_hex),
                    bytes.fromhex(case["message_hex"]),
                    bytes.fromhex(case["signature_hex"]),
                    bytes.fromhex(case["context_hex"]),
                )
                self.assertIs(got, case["expected"])

    def test_profile_v2_examples(self) -> None:
        profile = self.vectors["profile_v2_examples"]
        for name in ("signed_tree_head", "monitor_report"):
            item = profile[name]
            with self.subTest(example=name):
                self.assertTrue(
                    ml_dsa_65.verify(
                        base64.b64decode(item["public_key_base64"], validate=True),
                        bytes.fromhex(item["signed_message_hex"]),
                        base64.b64decode(item["signature_base64"], validate=True),
                    )
                )

    def test_never_raises_on_garbage(self) -> None:
        keys = self.vectors["keys"]
        pk = bytes.fromhex(keys[0]["public_key_hex"])
        for args in (
            (None, b"", b""),
            (pk, "text", bytes(3309)),
            (pk, b"", bytes(3309)),
            (bytes(1952), b"", bytes(3309)),
            (pk, b"", b"\xff" * 3309),
            (pk, b"", bytes(3309), bytes(256)),
            (pk, b"", bytes(3309), "ctx"),
        ):
            self.assertIs(ml_dsa_65.verify(*args), False)

    def test_verify_time_budget(self) -> None:
        case = next(c for c in self.vectors["cases"] if c["expected"])
        pk = bytes.fromhex(self.vectors["keys"][case["key"]]["public_key_hex"])
        start = time.perf_counter()
        ml_dsa_65.verify(
            pk,
            bytes.fromhex(case["message_hex"]),
            bytes.fromhex(case["signature_hex"]),
            bytes.fromhex(case["context_hex"]),
        )
        self.assertLess(time.perf_counter() - start, 2.0)


if __name__ == "__main__":
    unittest.main()
